// Mock data for the real estate platform demo

export interface Propiedad {
  id: string
  titulo: string
  precio: number
  ubicacion: string
  ciudad: string
  habitaciones: number
  banos: number
  area: number
  tipo: 'Casa' | 'Apartamento' | 'Oficina' | 'Local' | 'Terreno'
  estado: 'Disponible' | 'En negociación' | 'Vendida' | 'Arrendada'
  descripcion: string
  imagen: string
  imagenes: string[]
  vistas: number
  leads: number
  broker: string
  brokerId: string
  fechaPublicacion: string
  destacada: boolean
  comisionCompartida: boolean
  porcentajeComision?: number
}

export interface Broker {
  id: string
  nombre: string
  email: string
  telefono: string
  agencia: string
  avatar: string
  propiedades: number
  ventas: number
  calificacion: number
}

export interface Lead {
  id: string
  nombre: string
  email: string
  telefono: string
  propiedadId: string
  propiedadTitulo: string
  fecha: string
  estado: 'Nuevo' | 'Contactado' | 'En seguimiento' | 'Cerrado' | 'Perdido'
  brokerId: string
}

export interface Agente {
  id: string
  nombre: string
  email: string
  telefono: string
  propiedadesAsignadas: number
  brokerId: string
  avatar: string
}

export const brokers: Broker[] = [
  {
    id: 'b1',
    nombre: 'Carlos Mendoza',
    email: 'carlos@inmobiliaripro.com',
    telefono: '+51 999 111 222',
    agencia: 'InmobiliariaPro',
    avatar: 'https://i.pravatar.cc/150?img=11',
    propiedades: 8,
    ventas: 24,
    calificacion: 4.9,
  },
  {
    id: 'b2',
    nombre: 'María Torres',
    email: 'maria@eliterealty.com',
    telefono: '+51 999 333 444',
    agencia: 'Elite Realty',
    avatar: 'https://i.pravatar.cc/150?img=5',
    propiedades: 12,
    ventas: 31,
    calificacion: 4.8,
  },
  {
    id: 'b3',
    nombre: 'José Quispe',
    email: 'jose@capitalhouses.com',
    telefono: '+51 999 555 666',
    agencia: 'Capital Houses',
    avatar: 'https://i.pravatar.cc/150?img=15',
    propiedades: 5,
    ventas: 18,
    calificacion: 4.7,
  },
  {
    id: 'b4',
    nombre: 'Ana Paredes',
    email: 'ana@premiuminmobiliaria.com',
    telefono: '+51 999 777 888',
    agencia: 'Premium Inmobiliaria',
    avatar: 'https://i.pravatar.cc/150?img=9',
    propiedades: 9,
    ventas: 27,
    calificacion: 4.9,
  },
  {
    id: 'b5',
    nombre: 'Roberto Díaz',
    email: 'roberto@horizonte.com',
    telefono: '+51 999 888 999',
    agencia: 'Horizonte Inmobiliaria',
    avatar: 'https://i.pravatar.cc/150?img=3',
    propiedades: 6,
    ventas: 15,
    calificacion: 4.6,
  },
]

export const propiedades: Propiedad[] = [
  {
    id: 'p1',
    titulo: 'Penthouse de Lujo en Miraflores',
    precio: 850000,
    ubicacion: 'Av. Larco 1200, Miraflores',
    ciudad: 'Lima',
    habitaciones: 4,
    banos: 3,
    area: 280,
    tipo: 'Apartamento',
    estado: 'Disponible',
    descripcion: 'Espectacular penthouse con vista panorámica al mar. Acabados de primera, terraza privada, cocina gourmet y estacionamiento doble. Una joya arquitectónica en el corazón de Miraflores con acceso a todas las comodidades de la ciudad.',
    imagen: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
      'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&q=80',
    ],
    vistas: 342,
    leads: 8,
    broker: 'Carlos Mendoza',
    brokerId: 'b1',
    fechaPublicacion: '2025-01-10',
    destacada: true,
    comisionCompartida: true,
    porcentajeComision: 50,
  },
  {
    id: 'p2',
    titulo: 'Casa Moderna en San Isidro',
    precio: 620000,
    ubicacion: 'Calle Los Alamos 450, San Isidro',
    ciudad: 'Lima',
    habitaciones: 5,
    banos: 4,
    area: 380,
    tipo: 'Casa',
    estado: 'Disponible',
    descripcion: 'Hermosa casa de diseño contemporáneo con jardín, piscina y zona de BBQ. Ubicada en una de las zonas más exclusivas de Lima, con acabados de lujo y amplios espacios para toda la familia.',
    imagen: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      'https://images.unsplash.com/photo-1600047508788-786f3865b6d9?w=800&q=80',
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&q=80',
    ],
    vistas: 518,
    leads: 12,
    broker: 'María Torres',
    brokerId: 'b2',
    fechaPublicacion: '2025-01-15',
    destacada: true,
    comisionCompartida: true,
    porcentajeComision: 40,
  },
  {
    id: 'p3',
    titulo: 'Apartamento Vista al Mar en Barranco',
    precio: 320000,
    ubicacion: 'Av. El Sol 890, Barranco',
    ciudad: 'Lima',
    habitaciones: 3,
    banos: 2,
    area: 145,
    tipo: 'Apartamento',
    estado: 'Disponible',
    descripcion: 'Moderno apartamento con vista al mar desde el balcón. Diseño vanguardista, cocina integrada y sala de estar luminosa. Edificio con seguridad 24/7, gym y rooftop social.',
    imagen: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    ],
    vistas: 287,
    leads: 6,
    broker: 'José Quispe',
    brokerId: 'b3',
    fechaPublicacion: '2025-01-20',
    destacada: true,
    comisionCompartida: false,
  },
  {
    id: 'p4',
    titulo: 'Oficina Prime en San Isidro Financiero',
    precio: 480000,
    ubicacion: 'Av. Javier Prado 2450, San Isidro',
    ciudad: 'Lima',
    habitaciones: 0,
    banos: 4,
    area: 220,
    tipo: 'Oficina',
    estado: 'Disponible',
    descripcion: 'Oficina de primer nivel en el distrito financiero. Planta libre, sistema de aire acondicionado central, estacionamientos incluidos y acceso a sala de reuniones compartida.',
    imagen: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
      'https://images.unsplash.com/photo-1497366754035-f200581ddef7?w=800&q=80',
    ],
    vistas: 195,
    leads: 4,
    broker: 'Ana Paredes',
    brokerId: 'b4',
    fechaPublicacion: '2025-01-25',
    destacada: false,
    comisionCompartida: true,
    porcentajeComision: 45,
  },
  {
    id: 'p5',
    titulo: 'Casa Familiar en La Molina',
    precio: 395000,
    ubicacion: 'Calle Los Pinos 230, La Molina',
    ciudad: 'Lima',
    habitaciones: 4,
    banos: 3,
    area: 260,
    tipo: 'Casa',
    estado: 'Disponible',
    descripcion: 'Amplia casa en condominio cerrado con seguridad 24 horas. Jardín frontal y trasero, cuarto de servicio y lavandería. Excelente ubicación cerca de colegios y centros comerciales.',
    imagen: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
    ],
    vistas: 412,
    leads: 9,
    broker: 'Carlos Mendoza',
    brokerId: 'b1',
    fechaPublicacion: '2025-02-01',
    destacada: true,
    comisionCompartida: true,
    porcentajeComision: 35,
  },
  {
    id: 'p6',
    titulo: 'Studio Moderno en Jesús María',
    precio: 115000,
    ubicacion: 'Av. Salaverry 1200, Jesús María',
    ciudad: 'Lima',
    habitaciones: 1,
    banos: 1,
    area: 55,
    tipo: 'Apartamento',
    estado: 'Disponible',
    descripcion: 'Acogedor studio completamente equipado, ideal para jóvenes profesionales. Edificio nuevo con rooftop, área de coworking y conserjería. Excelente conectividad con transporte público.',
    imagen: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
    ],
    vistas: 328,
    leads: 7,
    broker: 'María Torres',
    brokerId: 'b2',
    fechaPublicacion: '2025-02-05',
    destacada: false,
    comisionCompartida: false,
  },
  {
    id: 'p7',
    titulo: 'Terreno Residencial en Surco',
    precio: 280000,
    ubicacion: 'Calle Monte Umbroso 340, Surco',
    ciudad: 'Lima',
    habitaciones: 0,
    banos: 0,
    area: 500,
    tipo: 'Terreno',
    estado: 'Disponible',
    descripcion: 'Terreno plano en zona residencial consolidada. Apto para construcción de casa o proyecto multifamiliar. Todos los servicios instalados. Excelente plusvalía en la zona.',
    imagen: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
    ],
    vistas: 156,
    leads: 3,
    broker: 'Roberto Díaz',
    brokerId: 'b5',
    fechaPublicacion: '2025-02-08',
    destacada: false,
    comisionCompartida: true,
    porcentajeComision: 50,
  },
  {
    id: 'p8',
    titulo: 'Departamento de Lujo en Lince',
    precio: 175000,
    ubicacion: 'Av. Arequipa 3400, Lince',
    ciudad: 'Lima',
    habitaciones: 2,
    banos: 2,
    area: 95,
    tipo: 'Apartamento',
    estado: 'En negociación',
    descripcion: 'Departamento moderno con acabados de primera. Sala comedor integrado, cocina americana equipada y dormitorio principal con walk-in closet. Edificio con ascensor y zona de estacionamiento.',
    imagen: 'https://images.unsplash.com/photo-1560185127-6a17f0e27f6c?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1560185127-6a17f0e27f6c?w=800&q=80',
    ],
    vistas: 267,
    leads: 5,
    broker: 'Ana Paredes',
    brokerId: 'b4',
    fechaPublicacion: '2025-02-10',
    destacada: false,
    comisionCompartida: false,
  },
  {
    id: 'p9',
    titulo: 'Casa con Piscina en Surco',
    precio: 520000,
    ubicacion: 'Av. Monterrico Norte 680, Surco',
    ciudad: 'Lima',
    habitaciones: 5,
    banos: 4,
    area: 340,
    tipo: 'Casa',
    estado: 'Disponible',
    descripcion: 'Impresionante casa con piscina privada, jardines y barbacoa. Cinco dormitorios, sala de juegos, estudio y triple cochera. Ubicada en urbanización exclusiva con vigilancia.',
    imagen: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
    ],
    vistas: 489,
    leads: 11,
    broker: 'Carlos Mendoza',
    brokerId: 'b1',
    fechaPublicacion: '2025-02-12',
    destacada: true,
    comisionCompartida: true,
    porcentajeComision: 40,
  },
  {
    id: 'p10',
    titulo: 'Local Comercial en Miraflores',
    precio: 350000,
    ubicacion: 'Av. Benavides 1890, Miraflores',
    ciudad: 'Lima',
    habitaciones: 0,
    banos: 2,
    area: 180,
    tipo: 'Local',
    estado: 'Disponible',
    descripcion: 'Local comercial en esquina con alto flujo peatonal. Vidriera amplia, depósito y baños para empleados. Zona de alta actividad comercial, ideal para retail o restaurante.',
    imagen: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80',
    ],
    vistas: 198,
    leads: 4,
    broker: 'María Torres',
    brokerId: 'b2',
    fechaPublicacion: '2025-02-15',
    destacada: false,
    comisionCompartida: true,
    porcentajeComision: 45,
  },
  {
    id: 'p11',
    titulo: 'Apartamento Nuevo en San Borja',
    precio: 245000,
    ubicacion: 'Av. San Luis 2300, San Borja',
    ciudad: 'Lima',
    habitaciones: 3,
    banos: 2,
    area: 120,
    tipo: 'Apartamento',
    estado: 'Disponible',
    descripcion: 'Apartamento a estrenar con vista a la ciudad. Tres dormitorios, sala-comedor, cocina equipada y lavandería. Edificio inteligente con control de acceso biométrico.',
    imagen: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80',
    ],
    vistas: 312,
    leads: 8,
    broker: 'José Quispe',
    brokerId: 'b3',
    fechaPublicacion: '2025-02-18',
    destacada: false,
    comisionCompartida: false,
  },
  {
    id: 'p12',
    titulo: 'Casa de Campo en Cieneguilla',
    precio: 185000,
    ubicacion: 'Km 32 Carretera a Cieneguilla',
    ciudad: 'Lima',
    habitaciones: 3,
    banos: 2,
    area: 450,
    tipo: 'Casa',
    estado: 'Disponible',
    descripcion: 'Casa de campo con amplio terreno, ideal para descanso y crianza. Árboles frutales, pozo propio y fácil acceso. A tan solo 40 minutos de Lima con paisajes naturales únicos.',
    imagen: 'https://images.unsplash.com/photo-1549517045-bc93de075e53?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1549517045-bc93de075e53?w=800&q=80',
    ],
    vistas: 223,
    leads: 5,
    broker: 'Roberto Díaz',
    brokerId: 'b5',
    fechaPublicacion: '2025-02-20',
    destacada: false,
    comisionCompartida: true,
    porcentajeComision: 50,
  },
  {
    id: 'p13',
    titulo: 'Penthouse en San Isidro',
    precio: 1200000,
    ubicacion: 'Calle Las Camelias 780, San Isidro',
    ciudad: 'Lima',
    habitaciones: 4,
    banos: 5,
    area: 420,
    tipo: 'Apartamento',
    estado: 'Disponible',
    descripcion: 'Extraordinario penthouse de doble altura. Terraza privada de 120m2 con jacuzzi y parrilla. Acabados importados, automatización del hogar y garaje para 3 autos.',
    imagen: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80',
    ],
    vistas: 567,
    leads: 15,
    broker: 'Ana Paredes',
    brokerId: 'b4',
    fechaPublicacion: '2025-02-22',
    destacada: true,
    comisionCompartida: true,
    porcentajeComision: 35,
  },
  {
    id: 'p14',
    titulo: 'Flat en Magdalena del Mar',
    precio: 145000,
    ubicacion: 'Jr. Leoncio Prado 1560, Magdalena',
    ciudad: 'Lima',
    habitaciones: 2,
    banos: 1,
    area: 75,
    tipo: 'Apartamento',
    estado: 'Disponible',
    descripcion: 'Acogedor flat con balcón en zona tranquila. Ideal para primera vivienda o inversión. Cerca de parques, centros de salud y transporte público.',
    imagen: 'https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=800&q=80',
    ],
    vistas: 178,
    leads: 3,
    broker: 'María Torres',
    brokerId: 'b2',
    fechaPublicacion: '2025-02-25',
    destacada: false,
    comisionCompartida: false,
  },
  {
    id: 'p15',
    titulo: 'Casa Duplex en Pueblo Libre',
    precio: 265000,
    ubicacion: 'Av. La Marina 2100, Pueblo Libre',
    ciudad: 'Lima',
    habitaciones: 3,
    banos: 3,
    area: 190,
    tipo: 'Casa',
    estado: 'Disponible',
    descripcion: 'Moderno duplex independiente con cochera para dos autos. Sala de estar en primer piso y sala de entretenimiento en segundo piso. Techos altos y buena iluminación natural.',
    imagen: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80',
    imagenes: [
      'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80',
    ],
    vistas: 245,
    leads: 6,
    broker: 'José Quispe',
    brokerId: 'b3',
    fechaPublicacion: '2025-02-28',
    destacada: false,
    comisionCompartida: true,
    porcentajeComision: 40,
  },
]

export const leads: Lead[] = [
  {
    id: 'l1',
    nombre: 'Fernando Castillo',
    email: 'fernando@gmail.com',
    telefono: '+51 987 111 222',
    propiedadId: 'p1',
    propiedadTitulo: 'Penthouse de Lujo en Miraflores',
    fecha: '2025-03-01',
    estado: 'Nuevo',
    brokerId: 'b1',
  },
  {
    id: 'l2',
    nombre: 'Lucía Vargas',
    email: 'lucia@hotmail.com',
    telefono: '+51 987 333 444',
    propiedadId: 'p2',
    propiedadTitulo: 'Casa Moderna en San Isidro',
    fecha: '2025-02-28',
    estado: 'Contactado',
    brokerId: 'b1',
  },
  {
    id: 'l3',
    nombre: 'Andrés Morales',
    email: 'andres@empresa.pe',
    telefono: '+51 987 555 666',
    propiedadId: 'p5',
    propiedadTitulo: 'Casa Familiar en La Molina',
    fecha: '2025-02-27',
    estado: 'En seguimiento',
    brokerId: 'b1',
  },
  {
    id: 'l4',
    nombre: 'Valentina Ríos',
    email: 'vale@gmail.com',
    telefono: '+51 987 777 888',
    propiedadId: 'p9',
    propiedadTitulo: 'Casa con Piscina en Surco',
    fecha: '2025-02-26',
    estado: 'En seguimiento',
    brokerId: 'b1',
  },
  {
    id: 'l5',
    nombre: 'Manuel Gutiérrez',
    email: 'manuel@outlook.com',
    telefono: '+51 987 999 000',
    propiedadId: 'p1',
    propiedadTitulo: 'Penthouse de Lujo en Miraflores',
    fecha: '2025-02-25',
    estado: 'Cerrado',
    brokerId: 'b1',
  },
  {
    id: 'l6',
    nombre: 'Patricia Soto',
    email: 'patricia@empresa.com',
    telefono: '+51 986 111 222',
    propiedadId: 'p2',
    propiedadTitulo: 'Casa Moderna en San Isidro',
    fecha: '2025-03-01',
    estado: 'Nuevo',
    brokerId: 'b2',
  },
  {
    id: 'l7',
    nombre: 'Ricardo Huanca',
    email: 'ricardo@gmail.com',
    telefono: '+51 986 333 444',
    propiedadId: 'p6',
    propiedadTitulo: 'Studio Moderno en Jesús María',
    fecha: '2025-02-28',
    estado: 'Contactado',
    brokerId: 'b2',
  },
  {
    id: 'l8',
    nombre: 'Carmen Lozano',
    email: 'carmen@hotmail.com',
    telefono: '+51 986 555 666',
    propiedadId: 'p10',
    propiedadTitulo: 'Local Comercial en Miraflores',
    fecha: '2025-02-27',
    estado: 'En seguimiento',
    brokerId: 'b2',
  },
  {
    id: 'l9',
    nombre: 'Diego Pacheco',
    email: 'diego@empresa.pe',
    telefono: '+51 986 777 888',
    propiedadId: 'p14',
    propiedadTitulo: 'Flat en Magdalena del Mar',
    fecha: '2025-02-26',
    estado: 'Perdido',
    brokerId: 'b2',
  },
  {
    id: 'l10',
    nombre: 'Sofía Herrera',
    email: 'sofia@gmail.com',
    telefono: '+51 986 999 000',
    propiedadId: 'p2',
    propiedadTitulo: 'Casa Moderna en San Isidro',
    fecha: '2025-02-25',
    estado: 'Cerrado',
    brokerId: 'b2',
  },
]

export const agentes: Agente[] = [
  {
    id: 'a1',
    nombre: 'Sofía Ramírez',
    email: 'sofia@inmobiliaripro.com',
    telefono: '+51 998 111 222',
    propiedadesAsignadas: 3,
    brokerId: 'b1',
    avatar: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: 'a2',
    nombre: 'Marco Flores',
    email: 'marco@inmobiliaripro.com',
    telefono: '+51 998 333 444',
    propiedadesAsignadas: 2,
    brokerId: 'b1',
    avatar: 'https://i.pravatar.cc/150?img=12',
  },
  {
    id: 'a3',
    nombre: 'Daniela Cruz',
    email: 'daniela@inmobiliaripro.com',
    telefono: '+51 998 555 666',
    propiedadesAsignadas: 2,
    brokerId: 'b1',
    avatar: 'https://i.pravatar.cc/150?img=5',
  },
  {
    id: 'a4',
    nombre: 'Raúl Chávez',
    email: 'raul@eliterealty.com',
    telefono: '+51 997 111 222',
    propiedadesAsignadas: 4,
    brokerId: 'b2',
    avatar: 'https://i.pravatar.cc/150?img=8',
  },
  {
    id: 'a5',
    nombre: 'Isabel Mendez',
    email: 'isabel@eliterealty.com',
    telefono: '+51 997 333 444',
    propiedadesAsignadas: 3,
    brokerId: 'b2',
    avatar: 'https://i.pravatar.cc/150?img=2',
  },
  {
    id: 'a6',
    nombre: 'Gonzalo Pinto',
    email: 'gonzalo@capitalhouses.com',
    telefono: '+51 996 111 222',
    propiedadesAsignadas: 2,
    brokerId: 'b3',
    avatar: 'https://i.pravatar.cc/150?img=17',
  },
  {
    id: 'a7',
    nombre: 'Natalia Ruiz',
    email: 'natalia@capitalhouses.com',
    telefono: '+51 996 333 444',
    propiedadesAsignadas: 1,
    brokerId: 'b3',
    avatar: 'https://i.pravatar.cc/150?img=4',
  },
  {
    id: 'a8',
    nombre: 'Alejandro Vega',
    email: 'alejandro@premiuminmobiliaria.com',
    telefono: '+51 995 111 222',
    propiedadesAsignadas: 4,
    brokerId: 'b4',
    avatar: 'https://i.pravatar.cc/150?img=20',
  },
]

export const formatPrecio = (precio: number) => {
  return new Intl.NumberFormat('es-PE', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(precio)
}

export const estadoColors: Record<string, string> = {
  Disponible: 'bg-accent/15 text-accent',
  'En negociación': 'bg-amber-100 text-amber-700',
  Vendida: 'bg-blue-100 text-blue-700',
  Arrendada: 'bg-purple-100 text-purple-700',
  Nuevo: 'bg-blue-100 text-blue-700',
  Contactado: 'bg-amber-100 text-amber-700',
  'En seguimiento': 'bg-purple-100 text-purple-700',
  Cerrado: 'bg-accent/15 text-accent',
  Perdido: 'bg-red-100 text-red-600',
}
